[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel={version="2.2.4",features=["sqlite","returning_clauses_for_sqlite_3_35"]}
#futures="0.3.28"
diesel_codegen="0.16.1"
dotenv = "0.15.0"

